name: vesuvius-scrolls
channels:
  - nvidia/label/cuda-12.0.1
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.7
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - cuda-nvcc=12.0.140
  - intel-openmp=2023.1.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.14
  - pandas=2.2.2
  - pip=24.0
  - python=3.11.9
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - readline=8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - acvl-utils==0.2.1
      - addict==2.4.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.9
      - aiosignal==1.3.1
      - albucore==0.0.23
      - albumentations==1.4.24
      - annotated-types==0.7.0
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - argparse==1.4.0
      - arrow==1.3.0
      - asciitree==0.3.3
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.15.0
      - batchgenerators==0.25.1
      - batchgeneratorsv2==0.2.1
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - blinker==1.8.2
      - boto3==1.35.44
      - botocore==1.35.44
      - brotli==1.1.0
      - cachetools==5.5.0
      - certifi==2024.7.4
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloud-files==4.27.0
      - cloud-volume==11.0.2
      - comm==0.2.2
      - compressed-segmentation==2.3.1
      - configargparse==1.7
      - connected-components-3d==3.18.0
      - contourpy==1.2.1
      - crackle-codec==0.15.1.dev2
      - crc32c==2.7.1
      - cycler==0.12.1
      - cython==3.0.10
      - dash==2.18.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - debugpy==1.8.2
      - decorator==5.1.1
      - deflate==0.7.0
      - defusedxml==0.7.1
      - dicom2nifti==2.5.0
      - dijkstra3d==1.15.1
      - dill==0.3.9
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - dracopy==1.4.1
      - dynamic-network-architectures==0.3.1
      - edt==2.4.1
      - efficientnet-pytorch==0.7.1
      - einops==0.8.0
      - executing==2.0.1
      - fasteners==0.19
      - fastjsonschema==2.20.0
      - fastremap==1.15.0
      - fft-conv-pytorch==1.2.0
      - filelock==3.15.4
      - fill-voids==2.0.7
      - flask==3.0.3
      - fonttools==4.53.1
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - future==1.0.0
      - gdown==5.2.0
      - gevent==24.10.3
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-api-core==2.21.0
      - google-auth==2.35.0
      - google-cloud-core==2.4.1
      - google-cloud-storage==2.18.2
      - google-crc32c==1.6.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.65.0
      - gputil==1.4.0
      - greenlet==3.1.1
      - grpcio==1.64.1
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.27.0
      - idna==3.7
      - imagecodecs==2024.9.22
      - imageio==2.34.2
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - inflection==0.5.1
      - iniconfig==2.0.0
      - ipykernel==6.29.5
      - ipython==8.26.0
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.11
      - kimimaro==4.1.2
      - kiwisolver==1.4.5
      - kornia==0.7.3
      - kornia-rs==0.1.5
      - lazy-loader==0.4
      - lightning-utilities==0.11.7
      - linecache2==1.0.0
      - mahotas==1.4.18
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - matplotlib-inline==0.1.7
      - microviewer==1.9.0
      - mistune==3.0.2
      - monai==1.3.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.17
      - munch==4.0.0
      - mypy-extensions==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - nibabel==5.3.2
      - nnunetv2==2.5.1
      - notebook==7.2.1
      - notebook-shim==0.2.4
      - nptyping==2.5.0
      - numcodecs==0.13.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.82
      - nvidia-nvtx-cu12==12.1.105
      - open3d==0.18.0
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - opt-einsum==3.3.0
      - orjson==3.10.9
      - overrides==7.7.0
      - packaging==24.1
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathos==0.3.3
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.2.2
      - plotly==5.24.1
      - pluggy==1.5.0
      - posix-ipc==1.1.1
      - pox==0.3.5
      - ppft==1.7.6.9
      - pretrainedmodels==0.7.4
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - propcache==0.2.0
      - proto-plus==1.24.0
      - protobuf==4.25.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pybind11==2.13.6
      - pycparser==2.22
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pydicom==3.0.1
      - pygments==2.18.0
      - pynrrd==1.0.0
      - pyparsing==3.1.2
      - pyquaternion==0.9.9
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pysimdjson==6.0.2
      - pysocks==1.7.1
      - pytest==8.3.3
      - python-gdcm==3.0.24.1
      - python-graphviz==0.20.3
      - python-json-logger==2.0.7
      - python-jsonschema-objects==0.5.5
      - pytorch-lightning==2.4.0
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - referencing==0.35.1
      - requests==2.32.3
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.19.0
      - rsa==4.9
      - s3transfer==0.10.3
      - safetensors==0.4.5
      - scikit-image==0.24.0
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - seaborn==0.13.2
      - segmentation-models-pytorch==0.3.4
      - send2trash==1.8.3
      - sentry-sdk==2.10.0
      - setproctitle==1.3.3
      - simpleitk==2.4.0
      - simplejpeg==1.7.6
      - simsimd==6.2.1
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.3
      - stringzilla==3.11.2
      - sympy==1.13.0
      - tenacity==9.0.0
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2024.7.2
      - timesformer-pytorch==0.4.1
      - timm==0.9.7
      - tinycss2==1.3.0
      - torch==2.3.1
      - torchdiffeq==0.2.4
      - torchinterp1d==1.1
      - torchmetrics==1.4.1
      - torchode==0.2.0
      - torchtyping==0.1.5
      - torchvision==0.18.1
      - tornado==6.4.1
      - tqdm==4.66.4
      - traceback2==1.4.0
      - traitlets==5.14.3
      - trimesh==4.4.9
      - triton==2.3.1
      - typed-argument-parser==1.10.1
      - typeguard==2.13.3
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - unittest2==1.1.0
      - uri-template==1.3.0
      - urllib3==2.2.2
      - wandb==0.17.5
      - waterz==0.8
      - wcwidth==0.2.13
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.11
      - xs3d==1.7.1
      - yacs==0.1.8
      - yarl==1.14.0
      - zarr==2.18.2
      - zipp==3.20.2
      - zope-event==5.0
      - zope-interface==7.1.0
      - zstandard==0.23.0
